import { writable } from 'svelte/store';
import type { C } from "../interfaces/countries-interface";

export const countriesStore = writable<C[]>([
        {
            continent: "Africa",
            countries: [
                {"code": "dz", "fullName": "Algeria"},
                {"code": "ao", "fullName": "Angola"},
                {"code": "bj", "fullName": "Benin"},
                {"code": "bw", "fullName": "Botswana"},
                {"code": "bf", "fullName": "Burkina Faso"},
                {"code": "bi", "fullName": "Burundi"},
                {"code": "cm", "fullName": "Cameroon"},
                {"code": "cv", "fullName": "Cape Verde"},
                {"code": "cf", "fullName": "Central African Republic"},
                {"code": "td", "fullName": "Chad"},
                {"code": "km", "fullName": "Comoros"},
                {"code": "cg", "fullName": "Congo"},
                {"code": "cd", "fullName": "Democratic Republic of Congo"},
                {"code": "ci", "fullName": "Ivory Coast"},
                {"code": "dj", "fullName": "Djibouti"},
                {"code": "eg", "fullName": "Egypt"},
                {"code": "gq", "fullName": "Equatorial Guinea"},
                {"code": "er", "fullName": "Eritrea"},
                {"code": "et", "fullName": "Ethiopia"},
                {"code": "ga", "fullName": "Gabon"},
                {"code": "gm", "fullName": "Gambia"},
                {"code": "gh", "fullName": "Ghana"},
                {"code": "gn", "fullName": "Guinea"},
                {"code": "gw", "fullName": "Guinea-Bissau"},
                {"code": "ke", "fullName": "Kenya"},
                {"code": "ls", "fullName": "Lesotho"},
                {"code": "lr", "fullName": "Liberia"},
                {"code": "ly", "fullName": "Libya"},
                {"code": "mg", "fullName": "Madagascar"},
                {"code": "mw", "fullName": "Malawi"},
                {"code": "ml", "fullName": "Mali"},
                {"code": "mr", "fullName": "Mauritania"},
                {"code": "mu", "fullName": "Mauritius"},
                {"code": "yt", "fullName": "Mayotte"},
                {"code": "ma", "fullName": "Morocco"},
                {"code": "mz", "fullName": "Mozambique"},
                {"code": "na", "fullName": "Namibia"},
                {"code": "ne", "fullName": "Niger"},
                {"code": "ng", "fullName": "Nigeria"},
                {"code": "st", "fullName": "São Tomé and Príncipe"},
                {"code": "sn", "fullName": "Senegal"},
                {"code": "sc", "fullName": "Seychelles"},
                {"code": "sl", "fullName": "Sierra Leone"},
                {"code": "so", "fullName": "Somalia"},
                {"code": "za", "fullName": "South Africa"},
                {"code": "ss", "fullName": "South Sudan"},
                {"code": "sd", "fullName": "Sudan"},
                {"code": "sz", "fullName": "Swaziland"},
                {"code": "tz", "fullName": "Tanzania"},
                {"code": "tg", "fullName": "Togo"},
                {"code": "tn", "fullName": "Tunisia"},
                {"code": "ug", "fullName": "Uganda"},
                {"code": "eh", "fullName": "Western Sahara"}
            ]
        },
        {
            continent: "America",
            countries: [
                {"code": "ca", "fullName": "Canada"},
                {"code": "us", "fullName": "United States of America"},
                {"code": "mx", "fullName": "Mexico"},
                {"code": "cu", "fullName": "Cuba"},
                {"code": "ht", "fullName": "Haiti"},
                {"code": "do", "fullName": "Dominican Republic"},
                {"code": "jm", "fullName": "Jamaica"},
                {"code": "bs", "fullName": "Bahamas"},
                {"code": "bz", "fullName": "Belize"},
                {"code": "gt", "fullName": "Guatemala"},
                {"code": "sv", "fullName": "El Salvador"},
                {"code": "hn", "fullName": "Honduras"},
                {"code": "ni", "fullName": "Nicaragua"},
                {"code": "cr", "fullName": "Costa Rica"},
                {"code": "pa", "fullName": "Panama"},
                {"code": "co", "fullName": "Colombia"},
                {"code": "ve", "fullName": "Venezuela"},
                {"code": "gy", "fullName": "Guyana"},
                {"code": "sr", "fullName": "Suriname"},
                {"code": "gf", "fullName": "French Guiana"},
                {"code": "ec", "fullName": "Ecuador"},
                {"code": "pe", "fullName": "Peru"},
                {"code": "bo", "fullName": "Bolivia"},
                {"code": "br", "fullName": "Brazil"},
                {"code": "py", "fullName": "Paraguay"},
                {"code": "uy", "fullName": "Uruguay"},
                {"code": "ar", "fullName": "Argentina"},
                {"code": "cl", "fullName": "Chile"},
                {"code": "ag", "fullName": "Antigua and Barbuda"},
                {"code": "bb", "fullName": "Barbados"},
                {"code": "dm", "fullName": "Dominica"},
                {"code": "gd", "fullName": "Grenada"},
                {"code": "kn", "fullName": "Saint Kitts and Nevis"},
                {"code": "lc", "fullName": "Saint Lucia"},
                {"code": "vc", "fullName": "Saint Vincent and the Grenadines"},
                {"code": "tt", "fullName": "Trinidad and Tobago"},
                {"code": "ai", "fullName": "Anguilla"},
                {"code": "aw", "fullName": "Aruba"},
                {"code": "bm", "fullName": "Bermuda"},
                {"code": "bq", "fullName": "Caribbean Netherlands"},
                {"code": "vg", "fullName": "British Virgin Islands"},
                {"code": "ky", "fullName": "Cayman Islands"},
                {"code": "cw", "fullName": "Curaçao"},
                {"code": "gl", "fullName": "Greenland"},
                {"code": "gp", "fullName": "Guadeloupe"},
                {"code": "mq", "fullName": "Martinique"},
                {"code": "ms", "fullName": "Montserrat"},
                {"code": "pr", "fullName": "Puerto Rico"},
                {"code": "bl", "fullName": "Saint Barthélemy"},
                {"code": "mf", "fullName": "Saint Martin"},
                {"code": "pm", "fullName": "Saint Pierre and Miquelon"},
                {"code": "sx", "fullName": "Sint Maarten"},
                {"code": "tc", "fullName": "Turks and Caicos Islands"},
                {"code": "vi", "fullName": "U.S. Virgin Islands"},
                {"code": "as","fullName": "American Samoa"},
                {"code": "gu","fullName": "Guam"},
                {"code": "mp","fullName": "Northern Mariana Islands"},
                {"code": "um","fullName": "United States Minor Outlying Islands"},
                {"code": "fk","fullName": "Falkland Islands"},
                {"code": "gs","fullName": "South Georgia and the South Sandwich Islands"}
            ]
        },
        {
            "continent": "Asia",
            "countries": [
                {"code": "af", "fullName": "Afghanistan"},
                {"code": "am", "fullName": "Armenia"},
                {"code": "az", "fullName": "Azerbaijan"},
                {"code": "bh", "fullName": "Bahrain"},
                {"code": "bd", "fullName": "Bangladesh"},
                {"code": "bt", "fullName": "Bhutan"},
                {"code": "bn", "fullName": "Brunei"},
                {"code": "kh", "fullName": "Cambodia"},
                {"code": "cn", "fullName": "China"},
                {"code": "cy", "fullName": "Cyprus"},
                {"code": "ge", "fullName": "Georgia"},
                {"code": "in", "fullName": "India"},
                {"code": "id", "fullName": "Indonesia"},
                {"code": "ir", "fullName": "Iran"},
                {"code": "iq", "fullName": "Iraq"},
                {"code": "il", "fullName": "Israel"},
                {"code": "jp", "fullName": "Japan"},
                {"code": "jo", "fullName": "Jordan"},
                {"code": "kz", "fullName": "Kazakhstan"},
                {"code": "kw", "fullName": "Kuwait"},
                {"code": "kg", "fullName": "Kyrgyzstan"},
                {"code": "la", "fullName": "Laos"},
                {"code": "lb", "fullName": "Lebanon"},
                {"code": "my", "fullName": "Malaysia"},
                {"code": "mv", "fullName": "Maldives"},
                {"code": "mn", "fullName": "Mongolia"},
                {"code": "mm", "fullName": "Myanmar (Burma)"},
                {"code": "np", "fullName": "Nepal"},
                {"code": "kp", "fullName": "North Korea"},
                {"code": "om", "fullName": "Oman"},
                {"code": "pk", "fullName": "Pakistan"},
                {"code": "ps", "fullName": "Palestine"},
                {"code": "ph", "fullName": "Philippines"},
                {"code": "qa", "fullName": "Qatar"},
                {"code": "sa", "fullName": "Saudi Arabia"},
                {"code": "sg", "fullName": "Singapore"},
                {"code": "kr", "fullName": "South Korea"},
                {"code": "lk", "fullName": "Sri Lanka"},
                {"code": "sy", "fullName": "Syria"},
                {"code": "tw", "fullName": "Taiwan"},
                {"code": "tj", "fullName": "Tajikistan"},
                {"code": "th", "fullName": "Thailand"},
                {"code": "tl", "fullName": "Timor-Leste (East Timor)"},
                {"code": "tr", "fullName": "Turkey"},
                {"code": "tm", "fullName": "Turkmenistan"},
                {"code": "ae", "fullName": "United Arab Emirates (UAE)"},
                {"code": "uz", "fullName": "Uzbekistan"},
                {"code": "vn", "fullName": "Vietnam"},
                {"code": "ye", "fullName": "Yemen"}
            ]
        },
        {
            "continent": "Europe",
            "countries": [
                {"code": "al", "fullName": "Albania"},
                {"code": "ad", "fullName": "Andorra"},
                {"code": "at", "fullName": "Austria"},
                {"code": "by", "fullName": "Belarus"},
                {"code": "be", "fullName": "Belgium"},
                {"code": "ba", "fullName": "Bosnia and Herzegovina"},
                {"code": "bg", "fullName": "Bulgaria"},
                {"code": "hr", "fullName": "Croatia"},
                {"code": "cy", "fullName": "Cyprus"},
                {"code": "cz", "fullName": "Czech Republic"},
                {"code": "dk", "fullName": "Denmark"},
                {"code": "ee", "fullName": "Estonia"},
                {"code": "fo", "fullName": "Faroe Islands"},
                {"code": "fi", "fullName": "Finland"},
                {"code": "fr", "fullName": "France"},
                {"code": "de", "fullName": "Germany"},
                {"code": "gi", "fullName": "Gibraltar"},
                {"code": "gr", "fullName": "Greece"},
                {"code": "gg", "fullName": "Guernsey"},
                {"code": "hu", "fullName": "Hungary"},
                {"code": "is", "fullName": "Iceland"},
                {"code": "ie", "fullName": "Ireland"},
                {"code": "im", "fullName": "Isle of Man"},
                {"code": "it", "fullName": "Italy"},
                {"code": "je", "fullName": "Jersey"},
                {"code": "lv", "fullName": "Latvia"},
                {"code": "li", "fullName": "Liechtenstein"},
                {"code": "lt", "fullName": "Lithuania"},
                {"code": "lu", "fullName": "Luxembourg"},
                {"code": "mk", "fullName": "North Macedonia"},
                {"code": "mt", "fullName": "Malta"},
                {"code": "md", "fullName": "Moldova"},
                {"code": "mc", "fullName": "Monaco"},
                {"code": "me", "fullName": "Montenegro"},
                {"code": "nl", "fullName": "Netherlands"},
                {"code": "no", "fullName": "Norway"},
                {"code": "pl", "fullName": "Poland"},
                {"code": "pt", "fullName": "Portugal"},
                {"code": "ro", "fullName": "Romania"},
                {"code": "ru", "fullName": "Russia"},
                {"code": "sm", "fullName": "San Marino"},
                {"code": "rs", "fullName": "Serbia"},
                {"code": "sk", "fullName": "Slovakia"},
                {"code": "si", "fullName": "Slovenia"},
                {"code": "es", "fullName": "Spain"},
                {"code": "se", "fullName": "Sweden"},
                {"code": "ch", "fullName": "Switzerland"},
                {"code": "ua", "fullName": "Ukraine"},
                {"code": "gb", "fullName": "United Kingdom"}
            ]
        },
        {
            "continent": "Oceania",
            "countries": [
                {"code": "as", "fullName": "American Samoa"},
                {"code": "au", "fullName": "Australia"},
                {"code": "ck", "fullName": "Cook Islands"},
                {"code": "fj", "fullName": "Fiji"},
                {"code": "pf", "fullName": "French Polynesia"},
                {"code": "gu", "fullName": "Guam"},
                {"code": "ki", "fullName": "Kiribati"},
                {"code": "mh", "fullName": "Marshall Islands"},
                {"code": "fm", "fullName": "Micronesia"},
                {"code": "nr", "fullName": "Nauru"},
                {"code": "nc", "fullName": "New Caledonia"},
                {"code": "nz", "fullName": "New Zealand"},
                {"code": "nu", "fullName": "Niue"},
                {"code": "nf", "fullName": "Norfolk Island"},
                {"code": "mp", "fullName": "Northern Mariana Islands"},
                {"code": "pw", "fullName": "Palau"},
                {"code": "pg", "fullName": "Papua New Guinea"},
                {"code": "pn", "fullName": "Pitcairn Islands"},
                {"code": "ws", "fullName": "Samoa"},
                {"code": "sb", "fullName": "Solomon Islands"},
                {"code": "tk", "fullName": "Tokelau"},
                {"code": "to", "fullName": "Tonga"},
                {"code": "tv", "fullName": "Tuvalu"},
                {"code": "vu", "fullName": "Vanuatu"},
                {"code": "wf", "fullName": "Wallis and Futuna"}
            ]
        }
]
);

//To prevent options from being affected by the deletion of already asked countries
export const allworldOptions = writable([]);
export const africaOptions = writable(['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cameroon', 'Cape Verde', 'Central African Republic', 'Chad', 'Comoros', 'Congo', 'Democratic Republic of Congo', 'Ivory Coast', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Mayotte', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'São Tomé and Príncipe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan', 'Swaziland', 'Tanzania', 'Togo', 'Tunisia', 'Uganda', 'Western Sahara']);
export const asiaOptions = writable(['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'Cyprus', 'Georgia', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar (Burma)', 'Nepal', 'North Korea', 'Oman', 'Pakistan', 'Palestine', 'Philippines', 'Qatar', 'Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Taiwan', 'Tajikistan', 'Thailand', 'Timor-Leste (East Timor)', 'Turkey', 'Turkmenistan', 'United Arab Emirates (UAE)', 'Uzbekistan', 'Vietnam', 'Yemen']);
export const americaOptions = writable(['Canada', 'United States of America', 'Mexico', 'Cuba', 'Haiti', 'Dominican Republic', 'Jamaica', 'Bahamas', 'Belize', 'Guatemala', 'El Salvador', 'Honduras', 'Nicaragua', 'Costa Rica', 'Panama', 'Colombia', 'Venezuela', 'Guyana', 'Suriname', 'French Guiana', 'Ecuador', 'Peru', 'Bolivia', 'Brazil', 'Paraguay', 'Uruguay', 'Argentina', 'Chile', 'Antigua and Barbuda', 'Barbados', 'Dominica', 'Grenada', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Trinidad and Tobago', 'Anguilla', 'Aruba', 'Bermuda', 'Caribbean Netherlands', 'British Virgin Islands', 'Cayman Islands', 'Curaçao', 'Greenland', 'Guadeloupe', 'Martinique', 'Montserrat', 'Puerto Rico', 'Saint Barthélemy', 'Saint Martin', 'Saint Pierre and Miquelon', 'Sint Maarten', 'Turks and Caicos Islands', 'U.S. Virgin Islands', 'American Samoa', 'Guam', 'Northern Mariana Islands', 'United States Minor Outlying Islands', 'Falkland Islands', 'South Georgia and the South Sandwich Islands']);
export const europeOptions = writable(['Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Faroe Islands', 'Finland', 'France', 'Germany', 'Gibraltar', 'Greece', 'Guernsey', 'Hungary', 'Iceland', 'Ireland', 'Isle of Man', 'Italy', 'Jersey', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'North Macedonia', 'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Ukraine', 'United Kingdom']);
export const oceaniaOptions = writable(['American Samoa', 'Australia', 'Cook Islands', 'Fiji', 'French Polynesia', 'Guam', 'Kiribati', 'Marshall Islands', 'Micronesia', 'Nauru', 'New Caledonia', 'New Zealand', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Palau', 'Papua New Guinea', 'Pitcairn Islands', 'Samoa', 'Solomon Islands', 'Tokelau', 'Tonga', 'Tuvalu', 'Vanuatu', 'Wallis and Futuna']);